# Generated by Django 3.1.14 on 2022-11-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='category_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='currency_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='price_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='subcategory_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='summary_selector',
        ),
        migrations.RemoveField(
            model_name='source',
            name='title_selector',
        ),
    ]
